services:
  dashboard-server:
    image: cmucal/cabot-dashboard-server
    build:
      context: ./cabot_dashboard_server
      dockerfile: Dockerfile
      x-bake:
        tags:
          - ${REGISTRY:-cmucal}/cabot-dashboard-server
        platforms:
          - linux/arm64
          - linux/amd64
        output:
          - type=registry
    ports:
      - "8000:8000"
    environment:
      - CABOT_DASHBOARD_LOG_LEVEL
      - CABOT_DASHBOARD_LOG_TO_FILE
      - CABOT_DASHBOARD_SESSION_TIMEOUT
      - CABOT_DASHBOARD_SESSION_SECRET
      - CABOT_DASHBOARD_MAX_ROBOTS
      - CABOT_DASHBOARD_POLL_TIMEOUT
      - CABOT_DASHBOARD_DEBUG_MODE
      - CABOT_DASHBOARD_ALLOWED_CABOT_IDS
      - CABOT_DASHBOARD_ACCESS_TOKEN_EXPIRE_MINUTES
      - CABOT_DASHBOARD_CLIENTS
      - CABOT_DASHBOARD_JWT_SECRET_KEY
      - CABOT_DASHBOARD_MICROSOFT_CLIENT_ID
      - CABOT_DASHBOARD_MICROSOFT_CLIENT_SECRET
      - CABOT_DASHBOARD_MICROSOFT_TENANT_ID
      - CABOT_DASHBOARD_CLIENTS
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  dashboard-client:
    image: cmucal/cabot-dashboard-client
    build:
      context: ./cabot_dashboard_client
      x-bake:
        tags:
          - ${REGISTRY:-cmucal}/cabot-dashboard-client
        platforms:
          - linux/arm64
          - linux/amd64
        output:
          - type=registry
    volumes:
      # for ssh
      - ${PWD}/id_cabot:/var/id_cabot
    environment:
      - CABOT_DASHBOARD_SERVER_URL
      - CABOT_DASHBOARD_API_KEY
      - CABOT_DASHBOARD_LOG_LEVEL
      - CABOT_DASHBOARD_LOG_TO_FILE
      - CABOT_DASHBOARD_POLLING_INTERVAL
      - CABOT_NAME
      - CABOT_DASHBOARD_CLIENT_ID
      - CABOT_DASHBOARD_CLIENT_SECRET
      - CABOT_DASHBOARD_DEBUG_MODE
      - CABOT_DASHBOARD_DEBUG_STATUS
      # for ssh
      - CABOT_DASHBOARD_USER_NAME=$USER
      - CABOT_DASHBOARD_ID_FILE=/var/id_cabot
    network_mode: host
    extra_hosts:
      # for ssh
      - "host_addr:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  logs:

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "10"

x-environment: &default-environment
  LOG_LEVEL: INFO
  LOG_TO_FILE: false
